version: 2

jobs:
  test:
    docker:
      - image: node:8.11.3-alpine
    steps:
      - checkout
      - run: apk --no-cache add ca-certificates
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths: node_modules
      - run:
          name: Eslint
          command: npm run lint
      - run:
          name: Mocha tests
          command: npm run coverage
      - run:
          name: Upload to codecov
          command: npm run codecov
      - run:
          name: Smoke tests
          command: bin/bids-validator tests/data/valid_headers/ --ignoreNiftiHeaders && bin/bids-validator tests/data/valid_headers/ --ignoreNiftiHeaders --json
  githubPagesTest:
    docker:
      - image: node:8.11.3-alpine
    steps:
      - checkout
      - run: apk --no-cache add ca-certificates
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run: apk --no-cache add rsync git python build-base openssh
      - run: git checkout -f gh-pages
      - run: npm install
      - run: if [ -z ${CIRCLE_PR_USERNAME}]; then npm install git+${CIRCLE_REPOSITORY_URL/git@github.com:/https://github.com/}\#${CIRCLE_SHA1}; else npm install git+https://git@github.com/${CIRCLE_PR_USERNAME}/${CIRCLE_PR_REPONAME}\#${CIRCLE_SHA1}; fi
      - run: ./node_modules/.bin/gulp build && rsync -av --exclude=".*" --exclude="node_modules" --exclude="src" --exclude="tests" . ~/web_version/
      - store_artifacts:
          path: ~/web_version/
  deployment:
    docker:
      - image: node:8.11.3-alpine
    steps:
      - add_ssh_keys:
          fingerprints:
            - '44:93:5a:f4:2b:2d:c1:8a:f2:8e:8b:e9:27:5f:93:25'
      - checkout
      - run: apk --no-cache add ca-certificates
      - run: apk --no-cache add git python build-base openssh
      # Publish to NPM
      - run: npm install
      - run: ./node_modules/.bin/npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL
      - run: git checkout -f $CIRCLE_TAG
      # Set the version number
      - run: sed -i -E "s/0.0.0/$CIRCLE_TAG/" package.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - githubPagesTest:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deployment:
          requires:
            - test
            - githubPagesTest
